# Changement sur la config générale du wiki
$conf['title'] = 'PostgreSQL.fr';
$conf['tagline'] = 'La communauté francophone de PostgreSQL, la base de données open source de référence';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 0;

# Config du template
$conf['template'] = 'bootstrap3';
$conf['plugin']['icons']['defaultSize'] = '18';
$conf['plugin']['icons']['loadMaterialDesignIcons'] = 0;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'readable';
$conf['tpl']['bootstrap3']['showThemeSwitcher'] = 1; #FIXME: A supprimer avant de passer en prod
$conf['tpl']['bootstrap3']['sidebarShowPageTitle'] = 0;
$conf['tpl']['bootstrap3']['showSearchForm'] = 'never';
$conf['tpl']['bootstrap3']['pageOnPanel'] = 0;
$conf['tpl']['bootstrap3']['showPageTools'] = 'logged';
$conf['tpl']['bootstrap3']['showPageId'] = 0;
$conf['tpl']['bootstrap3']['showBadges'] = 0;
$conf['tpl']['bootstrap3']['useAvatar'] = 'gravatar';
$conf['tpl']['bootstrap3']['showCookieLawBanner'] = 1;
$conf['tpl']['bootstrap3']['showPageInfo'] = 0;
$conf['tpl']['bootstrap3']['pageInfo'] = 'extension,date,editor,locked';
$conf['tpl']['bootstrap3']['showPageIcons'] = 0;
$conf['tpl']['bootstrap3']['pageIcons'] = 'social-share,permalink';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,pinterest,whatsapp,reddit,twitter,telegram,yammer';
