
- name: Deployer le theme pgdocs_fr
  copy:
    src: "{{ item.src }}"
    dest: "{{ pgdocs_fr_home }}/{{ item.dst }}"
    owner: www-data
    group: www-data
  with_items:
     - src: pgdocs_fr/theme
       dst:
     - src: pgdocs_fr/index.php
       dst:
